feat: Views
piero-vic/blog-app pull request #5
Opened 2022-03-08 19:00 UTC by piero-vic

2022-03-08 19:42 UTC, piero-vic commented
Hi @od-c0d3r 

I left you a note in the pull request description regarding the linter errors. I was hoping you could help me with some guidance or advice for this kind of cases. Other CSS frameworks like Bootstrap seem to work just fine with the Microverse linters. Shouldn't that also be the case for Tailwind?

2022-03-08 20:32 UTC, od-c0d3r commented
@piero-vic Thanks for your feedback, unlucky the our CR dashboard is distracting i didn't notice the note. 
however, i will look into it now.

2022-03-08 21:04 UTC, od-c0d3r commented
> Hi @od-c0d3r
> 
> I left you a note in the pull request description regarding the linter errors. I was hoping you could help me with some guidance or advice for this kind of cases. Other CSS frameworks like Bootstrap seem to work just fine with the Microverse linters. Shouldn't that also be the case for Tailwind?

It's okay to add exepction only for where you are using the `@tailwind` directive 

Example
```css
/* stylelint-disable /
@tailwind base;
@tailwind components;
@tailwind utilities;
/ stylelint-enable */
```

2022-03-08 22:59 UTC, piero-vic commented
Thanks @od-c0d3r. I will proceed to add the exception and submit for the next review.

2022-03-09 00:07 UTC, julie-ify requested changes
## Hi @piero-vic,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

- [ ] **[REQUIRED]** Kindly add instructions on how to create, migrate and seed your database in the README so that users can find all the commands needed to get your app running. Also, add a more detailed description of this project to make your README more descriptive.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-09 00:07 UTC, julie-ify commented on app/assets/stylesheets/application.tailwind.css
> +/* stylelint-enable */
- [ ] I received the error below when I run `rails s` to start your project server. Kindly fix this issue so that we can view your project and test all you implemented in your views codebase. You may check out this [thread](https://github.com/rails/tailwindcss-rails/issues/50) to see if you can find a solution.

<img width="655" alt="chrome_cMl5lDl3et" src="https://user-images.githubusercontent.com/81468675/157345400-f3f8e976-7102-4400-9a17-d2051e1b6914.png">

2022-03-09 00:07 UTC, julie-ify commented on app/views/users/show.html.erb
> +  </div>
- [ ] **[OPTIONAL]** I suggest you create a [partial](https://riptutorial.com/ruby-on-rails/example/2875/partials) for this repeated user information which is present in almost all the views you created. This makes you write less code and you can make your codebase DRY too.

2022-03-09 15:18 UTC, piero-vic commented on app/assets/stylesheets/application.tailwind.css
> +/* stylelint-enable */
Hi @julie-ify 
I got the same error when I reset the project. For Tailwind to work with Rails we need to run `./bin/dev` inside the project's root directory before running `rails s`. It's on the [TailwindCSS Docs](https://tailwindcss.com/docs/guides/ruby-on-rails). I'll make sure to include the instructions on the `README.md` file.

2022-03-09 17:39 UTC, elisha2kyakpo1 approved these changes
Hi @piero-vic, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-09 17:59 UTC, merged